import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Cloudflare/OpenNext build output (gitignored, generated by `cf:build`).
    // Without these, `npm run lint` scans thousands of bundled files and is
    // unusable as a gate on anyone who has run a Worker build locally.
    ".open-next/**",
    ".wrangler/**",
  ]),
]);

export default eslintConfig;
