import type { SupabaseClient } from "@supabase/supabase-js";
import type { CanonicalRespondent, IngestSummary } from "./canonical";

const CHUNK = 500;

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

async function insertAll(client: SupabaseClient, table: string, rows: object[]) {
  for (const batch of chunk(rows, CHUNK)) {
    const { error } = await client.from(table).insert(batch);
    if (error) throw new Error(`${table}: ${error.message}`);
  }
}

/**
 * Persist a validated canonical bundle into respondent / quant_response /
 * qual_observation, all stamped with the target tenant_id + study_id (§4.2).
 *
 * The caller MUST pass a client authorized for these writes. In the app this is
 * the service_role admin client used only AFTER the server has verified the
 * requester is an internal user (§6.3/§7.1) and the data passed validation.
 *
 * Respondent ids are generated by the adapter, so children can reference them
 * without a round-trip. Ordering matters: respondents first (FK targets).
 */
export async function persistRespondents(
  client: SupabaseClient,
  params: { tenantId: string; studyId: string; respondents: CanonicalRespondent[] },
): Promise<IngestSummary> {
  const { tenantId, studyId, respondents } = params;

  const respondentRows = respondents.map((r) => ({
    id: r.id,
    tenant_id: tenantId,
    study_id: studyId,
    segments: r.segments,
  }));
  const quantRows = respondents.flatMap((r) =>
    r.quant.map((q) => ({
      tenant_id: tenantId,
      study_id: studyId,
      respondent_id: r.id,
      metric_key: q.metric_key,
      value: q.value,
    })),
  );
  const qualRows = respondents.flatMap((r) =>
    r.qual.map((q) => ({
      tenant_id: tenantId,
      study_id: studyId,
      respondent_id: r.id,
      source: q.source,
      category: q.category,
      theme: q.theme,
      quote: q.quote,
    })),
  );

  await insertAll(client, "respondent", respondentRows);
  await insertAll(client, "quant_response", quantRows);
  await insertAll(client, "qual_observation", qualRows);

  return { respondents: respondentRows.length, quant: quantRows.length, qual: qualRows.length };
}
